// <auto-generated />
using System;
using Campaign.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Campaign.Infrastructure.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("campaign_number_seq");

            modelBuilder.HasSequence("case_number_seq");

            modelBuilder.Entity("Campaign.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CampaignNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("campaign_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_rate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetSegment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_segment");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("CampaignNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_campaigns_campaign_number");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Campaign.Domain.Entities.CaseStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_case_status_history");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_status_history_case_id");

                    b.ToTable("case_status_history", (string)null);
                });

            modelBuilder.Entity("Campaign.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<decimal>("ConversionProbability")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("conversion_probability");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("boolean")
                        .HasColumnName("is_priority");

                    b.Property<decimal>("RecommendationScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("recommendation_score");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.HasKey("Id")
                        .HasName("pk_offers");

                    b.HasIndex("SubscriberId")
                        .HasDatabaseName("ix_offers_subscriber_id");

                    b.HasIndex("CampaignId", "SubscriberId")
                        .IsUnique()
                        .HasDatabaseName("ix_offers_campaign_id_subscriber_id");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Campaign.Domain.Entities.OfferRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<short>("Stars")
                        .HasColumnType("smallint")
                        .HasColumnName("stars");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.HasKey("Id")
                        .HasName("pk_offer_ratings");

                    b.HasIndex("OfferId")
                        .IsUnique()
                        .HasDatabaseName("ix_offer_ratings_offer_id");

                    b.ToTable("offer_ratings", null, t =>
                        {
                            t.HasCheckConstraint("ck_offer_ratings_stars", "stars BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Campaign.Domain.Entities.OptimizationCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_expert_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("case_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("ConversionLift")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("conversion_lift");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpertNote")
                        .HasColumnType("text")
                        .HasColumnName("expert_note");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("segment");

                    b.Property<bool>("SlaBreached")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sla_breached");

                    b.Property<DateTimeOffset>("SlaDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_deadline");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_optimization_cases");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_optimization_cases_campaign_id");

                    b.HasIndex("CaseNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_optimization_cases_case_number");

                    b.HasIndex("AssignedExpertId", "Status")
                        .HasDatabaseName("ix_optimization_cases_assigned_expert_id_status");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("ix_optimization_cases_status_priority");

                    b.ToTable("optimization_cases", (string)null);
                });

            modelBuilder.Entity("Campaign.Domain.Entities.SubscriberProfile", b =>
                {
                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriber_id");

                    b.Property<int>("AvgMonthlyCallMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("avg_monthly_call_minutes");

                    b.Property<decimal>("AvgMonthlyDataGb")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("avg_monthly_data_gb");

                    b.Property<int>("ComplaintCount")
                        .HasColumnType("integer")
                        .HasColumnName("complaint_count");

                    b.Property<string>("CurrentPlan")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("current_plan");

                    b.Property<string>("CurrentSegment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("current_segment");

                    b.Property<int>("DaysSinceLastActivity")
                        .HasColumnType("integer")
                        .HasColumnName("days_since_last_activity");

                    b.Property<string>("GsmNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gsm_number");

                    b.Property<decimal>("MonthlySpendTl")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("monthly_spend_tl");

                    b.Property<int>("PackagePurchaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("package_purchase_count");

                    b.Property<decimal>("PastAcceptanceRate")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("past_acceptance_rate");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("integer")
                        .HasColumnName("tenure_months");

                    b.HasKey("SubscriberId")
                        .HasName("pk_subscriber_profiles");

                    b.ToTable("subscriber_profiles", (string)null);
                });

            modelBuilder.Entity("Campaign.Domain.Entities.CaseStatusHistory", b =>
                {
                    b.HasOne("Campaign.Domain.Entities.OptimizationCase", "Case")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_status_history_optimization_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Campaign.Domain.Entities.Offer", b =>
                {
                    b.HasOne("Campaign.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offers_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Campaign.Domain.Entities.OfferRating", b =>
                {
                    b.HasOne("Campaign.Domain.Entities.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offer_ratings_offers_offer_id");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Campaign.Domain.Entities.OptimizationCase", b =>
                {
                    b.HasOne("Campaign.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_optimization_cases_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Campaign.Domain.Entities.OptimizationCase", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
