// <auto-generated />
using System;
using Gamification.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gamification.Infrastructure.Migrations
{
    [DbContext(typeof(GamificationDbContext))]
    [Migration("20260722173508_InitialGamification")]
    partial class InitialGamification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gamification.Domain.Entities.Badge", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_badges");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("Gamification.Domain.Entities.ExpertBadge", b =>
                {
                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_id");

                    b.Property<string>("BadgeCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("badge_code");

                    b.Property<DateTimeOffset>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.HasKey("ExpertId", "BadgeCode")
                        .HasName("pk_expert_badges");

                    b.HasIndex("BadgeCode")
                        .HasDatabaseName("ix_expert_badges_badge_code");

                    b.ToTable("expert_badges", (string)null);
                });

            modelBuilder.Entity("Gamification.Domain.Entities.ExpertScore", b =>
                {
                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_id");

                    b.Property<int>("CompletedCaseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_case_count");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<int>("FastCompletionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("fast_completion_count");

                    b.Property<int>("RiskliKayipSavedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("riskli_kayip_saved_count");

                    b.Property<int>("TargetExceededCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("target_exceeded_count");

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_points");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExpertId")
                        .HasName("pk_expert_scores");

                    b.ToTable("expert_scores", (string)null);
                });

            modelBuilder.Entity("Gamification.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_point_transactions");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_point_transactions_event_id");

                    b.HasIndex("ExpertId", "CreatedAt")
                        .HasDatabaseName("ix_point_transactions_expert_id_created_at");

                    b.ToTable("point_transactions", (string)null);
                });

            modelBuilder.Entity("Gamification.Domain.Entities.SegmentCompletionCount", b =>
                {
                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_id");

                    b.Property<string>("Segment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("segment");

                    b.Property<int>("CompletedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_count");

                    b.HasKey("ExpertId", "Segment")
                        .HasName("pk_segment_completion_counts");

                    b.ToTable("segment_completion_counts", (string)null);
                });

            modelBuilder.Entity("Gamification.Domain.Entities.ExpertBadge", b =>
                {
                    b.HasOne("Gamification.Domain.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expert_badges_badges_badge_code");

                    b.Navigation("Badge");
                });
#pragma warning restore 612, 618
        }
    }
}
